meta_product_name: "F.A.M.E Festival"
meta_title: "F.A.M.E Festival - #food #art #music & #environnement"
meta_description: "Relevant description"
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
